name: 'test'
on:
    push:
        branches:
            - main
    pull_request:
      branches: [ main ]

jobs:
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - run: npm ci
            - run: npm run lint
            - run: npm test
            - run: npm run prepare
            - name: verify dist/ is up to date
              run: git diff --exit-code --stat dist/
            - name: '[main] snyk monitor'
              if: github.ref == 'refs/heads/main'
              uses: snyk/actions/node@master
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                  args: --prune-repeated-subdependencies --target-reference=${{ github.ref_name }}
                  command: monitor
